export const ADD_TO_PLANNER = "ADD_TO_PLANNER";
export const REMOVE_FROM_PLANNER = "REMOVE_FROM_PLANNER";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
